import os

def _get(name: str) -> str:
    value = os.getenv(name)
    if value is None:
        raise ValueError(f"Missing required environment variable: {name}")
    return value

START_YEAR = 2024
END_YEAR = 2030

YELLOW_TAXI_BUCKET_NAME = _get("YELLOW_TAXI_BUCKET_NAME")
YELLOW_TAXI_S3_STAGING_DIR = _get("YELLOW_TAXI_S3_STAGING_DIR")
YELLOW_TAXI_AWS_REGION = _get("YELLOW_TAXI_AWS_REGION")

YELLOW_TAXI_RAW_FOLDER = _get("YELLOW_TAXI_RAW_FOLDER")
YELLOW_TAXI_PROCESSED_FOLDER = _get("YELLOW_TAXI_PROCESSED_FOLDER")

TLC_BASE_URL = _get("TLC_BASE_URL")
YELLOW_TAXI_DATASET = _get("YELLOW_TAXI_DATASET")
YELLOW_TAXI_TABLE_NAME = _get("YELLOW_TAXI_TABLE_NAME")
YELLOW_TAXI_ENRICHED_TABLE_NAME = _get("YELLOW_TAXI_ENRICHED_TABLE_NAME")
YELLOW_TAXI_DATABASE = _get("YELLOW_TAXI_DATABASE")
