from dotenv import load_dotenv
import os

load_dotenv()

YELLOW_TAXI_BUCKET_NAME = os.getenv("YELLOW_TAXI_BUCKET_NAME")
YELLOW_TAXI_S3_STAGING_DIR = os.getenv("YELLOW_TAXI_S3_STAGING_DIR")
YELLOW_TAXI_AWS_REGION = os.getenv("YELLOW_TAXI_AWS_REGION")

YELLOW_TAXI_DATASET = os.getenv("YELLOW_TAXI_DATASET")
YELLOW_TAXI_RAW_FOLDER = os.getenv("YELLOW_TAXI_RAW_FOLDER", "raw_data/yellow_taxi")
YELLOW_TAXI_PROCESSED_FOLDER = os.getenv("YELLOW_TAXI_PROCESSED_FOLDER", "processed_data/yellow_taxi")
YELLOW_TAXI_TABLE_NAME = os.getenv("YELLOW_TAXI_TABLE_NAME")
YELLOW_TAXI_ENRICHED_TABLE_NAME = os.getenv("YELLOW_TAXI_ENRICHED_TABLE_NAME")
YELLOW_TAXI_DATABASE = os.getenv("YELLOW_TAXI_DATABASE")
TLC_BASE_URL = os.getenv("TLC_BASE_URL")